/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "../j2735/J2735-AddGrpB.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_AddGrpB_Angle_H_
#define	_AddGrpB_Angle_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AddGrpB_Angle */
typedef long	 AddGrpB_Angle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AddGrpB_Angle;
asn_struct_free_f AddGrpB_Angle_free;
asn_struct_print_f AddGrpB_Angle_print;
asn_constr_check_f AddGrpB_Angle_constraint;
jer_type_encoder_f AddGrpB_Angle_encode_jer;
per_type_decoder_f AddGrpB_Angle_decode_uper;
per_type_encoder_f AddGrpB_Angle_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AddGrpB_Angle_H_ */
#include "asn_internal.h"
