/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SPAT"
 * 	found in "../j2735/J2735-SPAT.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_AdvisorySpeedType_H_
#define	_AdvisorySpeedType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdvisorySpeedType {
	AdvisorySpeedType_none	= 0,
	AdvisorySpeedType_greenwave	= 1,
	AdvisorySpeedType_ecoDrive	= 2,
	AdvisorySpeedType_transit	= 3
	/*
	 * Enumeration is extensible
	 */
} e_AdvisorySpeedType;

/* AdvisorySpeedType */
typedef long	 AdvisorySpeedType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AdvisorySpeedType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AdvisorySpeedType;
extern const asn_INTEGER_specifics_t asn_SPC_AdvisorySpeedType_specs_1;
asn_struct_free_f AdvisorySpeedType_free;
asn_struct_print_f AdvisorySpeedType_print;
asn_constr_check_f AdvisorySpeedType_constraint;
jer_type_encoder_f AdvisorySpeedType_encode_jer;
per_type_decoder_f AdvisorySpeedType_decode_uper;
per_type_encoder_f AdvisorySpeedType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AdvisorySpeedType_H_ */
#include "asn_internal.h"
