/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ProbeVehicleData"
 * 	found in "../j2735/J2735-ProbeVehicleData.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_AxleLocation_H_
#define	_AxleLocation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AxleLocation */
typedef long	 AxleLocation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AxleLocation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AxleLocation;
asn_struct_free_f AxleLocation_free;
asn_struct_print_f AxleLocation_print;
asn_constr_check_f AxleLocation_constraint;
jer_type_encoder_f AxleLocation_encode_jer;
per_type_decoder_f AxleLocation_decode_uper;
per_type_encoder_f AxleLocation_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AxleLocation_H_ */
#include "asn_internal.h"
