/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "../j2735/J2735-Common.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_CodeWord_H_
#define	_CodeWord_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CodeWord */
typedef OCTET_STRING_t	 CodeWord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CodeWord;
asn_struct_free_f CodeWord_free;
asn_struct_print_f CodeWord_print;
asn_constr_check_f CodeWord_constraint;
jer_type_encoder_f CodeWord_encode_jer;
per_type_decoder_f CodeWord_decode_uper;
per_type_encoder_f CodeWord_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CodeWord_H_ */
#include "asn_internal.h"
