/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "../j2735/J2735-AddGrpB.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_Day_H_
#define	_Day_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Day */
typedef long	 Day_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Day_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Day;
asn_struct_free_f Day_free;
asn_struct_print_f Day_print;
asn_constr_check_f Day_constraint;
jer_type_encoder_f Day_encode_jer;
per_type_decoder_f Day_decode_uper;
per_type_encoder_f Day_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Day_H_ */
#include "asn_internal.h"
