/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "../j2735/J2735-AddGrpB.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_Holiday_H_
#define	_Holiday_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Holiday {
	Holiday_weekday	= 0,
	Holiday_holiday	= 1
} e_Holiday;

/* Holiday */
typedef long	 Holiday_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Holiday_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Holiday;
extern const asn_INTEGER_specifics_t asn_SPC_Holiday_specs_1;
asn_struct_free_f Holiday_free;
asn_struct_print_f Holiday_print;
asn_constr_check_f Holiday_constraint;
jer_type_encoder_f Holiday_encode_jer;
per_type_decoder_f Holiday_decode_uper;
per_type_encoder_f Holiday_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Holiday_H_ */
#include "asn_internal.h"
