/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TravelerInformation"
 * 	found in "../j2735/J2735-TravelerInformation.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_ITIStextPhrase_H_
#define	_ITIStextPhrase_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IA5String.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ITIStextPhrase */
typedef IA5String_t	 ITIStextPhrase_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ITIStextPhrase_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ITIStextPhrase;
asn_struct_free_f ITIStextPhrase_free;
asn_struct_print_f ITIStextPhrase_print;
asn_constr_check_f ITIStextPhrase_constraint;
jer_type_encoder_f ITIStextPhrase_encode_jer;
per_type_decoder_f ITIStextPhrase_decode_uper;
per_type_encoder_f ITIStextPhrase_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ITIStextPhrase_H_ */
#include "asn_internal.h"
