/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SPAT"
 * 	found in "../j2735/J2735-SPAT.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_MovementPhaseState_H_
#define	_MovementPhaseState_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MovementPhaseState {
	MovementPhaseState_unavailable	= 0,
	MovementPhaseState_dark	= 1,
	MovementPhaseState_stop_Then_Proceed	= 2,
	MovementPhaseState_stop_And_Remain	= 3,
	MovementPhaseState_pre_Movement	= 4,
	MovementPhaseState_permissive_Movement_Allowed	= 5,
	MovementPhaseState_protected_Movement_Allowed	= 6,
	MovementPhaseState_permissive_clearance	= 7,
	MovementPhaseState_protected_clearance	= 8,
	MovementPhaseState_caution_Conflicting_Traffic	= 9
} e_MovementPhaseState;

/* MovementPhaseState */
typedef long	 MovementPhaseState_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MovementPhaseState_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MovementPhaseState;
extern const asn_INTEGER_specifics_t asn_SPC_MovementPhaseState_specs_1;
asn_struct_free_f MovementPhaseState_free;
asn_struct_print_f MovementPhaseState_print;
asn_constr_check_f MovementPhaseState_constraint;
jer_type_encoder_f MovementPhaseState_encode_jer;
per_type_decoder_f MovementPhaseState_decode_uper;
per_type_encoder_f MovementPhaseState_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MovementPhaseState_H_ */
#include "asn_internal.h"
