/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "../j2735/J2735-Common.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_NodeOffsetPointXY_H_
#define	_NodeOffsetPointXY_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NodeOffsetPointXY_PR {
	NodeOffsetPointXY_PR_NOTHING,	/* No components present */
	NodeOffsetPointXY_PR_node_XY1,
	NodeOffsetPointXY_PR_node_XY2,
	NodeOffsetPointXY_PR_node_XY3,
	NodeOffsetPointXY_PR_node_XY4,
	NodeOffsetPointXY_PR_node_XY5,
	NodeOffsetPointXY_PR_node_XY6,
	NodeOffsetPointXY_PR_node_LatLon,
	NodeOffsetPointXY_PR_regional
} NodeOffsetPointXY_PR;

/* Forward declarations */
struct Node_XY_20b;
struct Node_XY_22b;
struct Node_XY_24b;
struct Node_XY_26b;
struct Node_XY_28b;
struct Node_XY_32b;
struct Node_LLmD_64b;
struct Reg_NodeOffsetPointXY;

/* NodeOffsetPointXY */
typedef struct NodeOffsetPointXY {
	NodeOffsetPointXY_PR present;
	union NodeOffsetPointXY_u {
		struct Node_XY_20b	*node_XY1;
		struct Node_XY_22b	*node_XY2;
		struct Node_XY_24b	*node_XY3;
		struct Node_XY_26b	*node_XY4;
		struct Node_XY_28b	*node_XY5;
		struct Node_XY_32b	*node_XY6;
		struct Node_LLmD_64b	*node_LatLon;
		struct Reg_NodeOffsetPointXY	*regional;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NodeOffsetPointXY_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeOffsetPointXY;
extern asn_CHOICE_specifics_t asn_SPC_NodeOffsetPointXY_specs_1;
extern asn_TYPE_member_t asn_MBR_NodeOffsetPointXY_1[8];
extern asn_per_constraints_t asn_PER_type_NodeOffsetPointXY_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Node-XY-20b.h"
#include "Node-XY-22b.h"
#include "Node-XY-24b.h"
#include "Node-XY-26b.h"
#include "Node-XY-28b.h"
#include "Node-XY-32b.h"
#include "Node-LLmD-64b.h"
#include "RegionalExtension.h"

#endif	/* _NodeOffsetPointXY_H_ */
#include "asn_internal.h"
