/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TravelerInformation"
 * 	found in "../j2735/J2735-TravelerInformation.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_NodeOffsetPointLL_H_
#define	_NodeOffsetPointLL_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NodeOffsetPointLL_PR {
	NodeOffsetPointLL_PR_NOTHING,	/* No components present */
	NodeOffsetPointLL_PR_node_LL1,
	NodeOffsetPointLL_PR_node_LL2,
	NodeOffsetPointLL_PR_node_LL3,
	NodeOffsetPointLL_PR_node_LL4,
	NodeOffsetPointLL_PR_node_LL5,
	NodeOffsetPointLL_PR_node_LL6,
	NodeOffsetPointLL_PR_node_LatLon,
	NodeOffsetPointLL_PR_regional
} NodeOffsetPointLL_PR;

/* Forward declarations */
struct Node_LL_24B;
struct Node_LL_28B;
struct Node_LL_32B;
struct Node_LL_36B;
struct Node_LL_44B;
struct Node_LL_48B;
struct Node_LLmD_64b;
struct Reg_NodeOffsetPointLL;

/* NodeOffsetPointLL */
typedef struct NodeOffsetPointLL {
	NodeOffsetPointLL_PR present;
	union NodeOffsetPointLL_u {
		struct Node_LL_24B	*node_LL1;
		struct Node_LL_28B	*node_LL2;
		struct Node_LL_32B	*node_LL3;
		struct Node_LL_36B	*node_LL4;
		struct Node_LL_44B	*node_LL5;
		struct Node_LL_48B	*node_LL6;
		struct Node_LLmD_64b	*node_LatLon;
		struct Reg_NodeOffsetPointLL	*regional;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NodeOffsetPointLL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeOffsetPointLL;
extern asn_CHOICE_specifics_t asn_SPC_NodeOffsetPointLL_specs_1;
extern asn_TYPE_member_t asn_MBR_NodeOffsetPointLL_1[8];
extern asn_per_constraints_t asn_PER_type_NodeOffsetPointLL_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Node-LL-24B.h"
#include "Node-LL-28B.h"
#include "Node-LL-32B.h"
#include "Node-LL-36B.h"
#include "Node-LL-44B.h"
#include "Node-LL-48B.h"
#include "Node-LLmD-64b.h"
#include "RegionalExtension.h"

#endif	/* _NodeOffsetPointLL_H_ */
#include "asn_internal.h"
