/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "../j2735/J2735-Common.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_NodeListXY_H_
#define	_NodeListXY_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NodeListXY_PR {
	NodeListXY_PR_NOTHING,	/* No components present */
	NodeListXY_PR_nodes,
	NodeListXY_PR_computed
	/* Extensions may appear below */
	
} NodeListXY_PR;

/* Forward declarations */
struct NodeSetXY;
struct ComputedLane;

/* NodeListXY */
typedef struct NodeListXY {
	NodeListXY_PR present;
	union NodeListXY_u {
		struct NodeSetXY	*nodes;
		struct ComputedLane	*computed;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NodeListXY_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeListXY;
extern asn_CHOICE_specifics_t asn_SPC_NodeListXY_specs_1;
extern asn_TYPE_member_t asn_MBR_NodeListXY_1[2];
extern asn_per_constraints_t asn_PER_type_NodeListXY_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NodeSetXY.h"
#include "ComputedLane.h"

#endif	/* _NodeListXY_H_ */
#include "asn_internal.h"
