/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TravelerInformation"
 * 	found in "../j2735/J2735-TravelerInformation.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_NodeListLL_H_
#define	_NodeListLL_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NodeListLL_PR {
	NodeListLL_PR_NOTHING,	/* No components present */
	NodeListLL_PR_nodes
	/* Extensions may appear below */
	
} NodeListLL_PR;

/* Forward declarations */
struct NodeSetLL;

/* NodeListLL */
typedef struct NodeListLL {
	NodeListLL_PR present;
	union NodeListLL_u {
		struct NodeSetLL	*nodes;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NodeListLL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeListLL;
extern asn_CHOICE_specifics_t asn_SPC_NodeListLL_specs_1;
extern asn_TYPE_member_t asn_MBR_NodeListLL_1[1];
extern asn_per_constraints_t asn_PER_type_NodeListLL_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NodeSetLL.h"

#endif	/* _NodeListLL_H_ */
#include "asn_internal.h"
