/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TravelerInformation"
 * 	found in "../j2735/J2735-TravelerInformation.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_OffsetSystem_H_
#define	_OffsetSystem_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Zoom.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OffsetSystem__offset_PR {
	OffsetSystem__offset_PR_NOTHING,	/* No components present */
	OffsetSystem__offset_PR_xy,
	OffsetSystem__offset_PR_ll
} OffsetSystem__offset_PR;

/* Forward declarations */
struct NodeListXY;
struct NodeListLL;

/* OffsetSystem */
typedef struct OffsetSystem {
	Zoom_t	*scale;	/* OPTIONAL */
	struct OffsetSystem__offset {
		OffsetSystem__offset_PR present;
		union OffsetSystem__offset_u {
			struct NodeListXY	*xy;
			struct NodeListLL	*ll;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} offset;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OffsetSystem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OffsetSystem;
extern asn_SEQUENCE_specifics_t asn_SPC_OffsetSystem_specs_1;
extern asn_TYPE_member_t asn_MBR_OffsetSystem_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NodeListXY.h"
#include "NodeListLL.h"

#endif	/* _OffsetSystem_H_ */
#include "asn_internal.h"
