/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SPAT"
 * 	found in "../j2735/J2735-SPAT.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_PedestrianBicycleDetect_H_
#define	_PedestrianBicycleDetect_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PedestrianBicycleDetect */
typedef BOOLEAN_t	 PedestrianBicycleDetect_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PedestrianBicycleDetect;
asn_struct_free_f PedestrianBicycleDetect_free;
asn_struct_print_f PedestrianBicycleDetect_print;
asn_constr_check_f PedestrianBicycleDetect_constraint;
jer_type_encoder_f PedestrianBicycleDetect_encode_jer;
per_type_decoder_f PedestrianBicycleDetect_decode_uper;
per_type_encoder_f PedestrianBicycleDetect_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PedestrianBicycleDetect_H_ */
#include "asn_internal.h"
