/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PersonalSafetyMessage"
 * 	found in "../j2735/J2735-PersonalSafetyMessage.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_PersonalCrossingInProgress_H_
#define	_PersonalCrossingInProgress_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PersonalCrossingInProgress */
typedef BOOLEAN_t	 PersonalCrossingInProgress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PersonalCrossingInProgress;
asn_struct_free_f PersonalCrossingInProgress_free;
asn_struct_print_f PersonalCrossingInProgress_print;
asn_constr_check_f PersonalCrossingInProgress_constraint;
jer_type_encoder_f PersonalCrossingInProgress_encode_jer;
per_type_decoder_f PersonalCrossingInProgress_decode_uper;
per_type_encoder_f PersonalCrossingInProgress_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PersonalCrossingInProgress_H_ */
#include "asn_internal.h"
