/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PersonalSafetyMessage"
 * 	found in "../j2735/J2735-PersonalSafetyMessage.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_PersonalCrossingRequest_H_
#define	_PersonalCrossingRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PersonalCrossingRequest */
typedef BOOLEAN_t	 PersonalCrossingRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PersonalCrossingRequest;
asn_struct_free_f PersonalCrossingRequest_free;
asn_struct_print_f PersonalCrossingRequest_print;
asn_constr_check_f PersonalCrossingRequest_constraint;
jer_type_encoder_f PersonalCrossingRequest_encode_jer;
per_type_decoder_f PersonalCrossingRequest_decode_uper;
per_type_encoder_f PersonalCrossingRequest_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PersonalCrossingRequest_H_ */
#include "asn_internal.h"
