/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PersonalSafetyMessage"
 * 	found in "../j2735/J2735-PersonalSafetyMessage.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_PublicSafetyAndRoadWorkerActivity_H_
#define	_PublicSafetyAndRoadWorkerActivity_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PublicSafetyAndRoadWorkerActivity {
	PublicSafetyAndRoadWorkerActivity_unavailable	= 0,
	PublicSafetyAndRoadWorkerActivity_workingOnRoad	= 1,
	PublicSafetyAndRoadWorkerActivity_settingUpClosures	= 2,
	PublicSafetyAndRoadWorkerActivity_respondingToEvents	= 3,
	PublicSafetyAndRoadWorkerActivity_directingTraffic	= 4,
	PublicSafetyAndRoadWorkerActivity_otherActivities	= 5
} e_PublicSafetyAndRoadWorkerActivity;

/* PublicSafetyAndRoadWorkerActivity */
typedef BIT_STRING_t	 PublicSafetyAndRoadWorkerActivity_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PublicSafetyAndRoadWorkerActivity_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PublicSafetyAndRoadWorkerActivity;
asn_struct_free_f PublicSafetyAndRoadWorkerActivity_free;
asn_struct_print_f PublicSafetyAndRoadWorkerActivity_print;
asn_constr_check_f PublicSafetyAndRoadWorkerActivity_constraint;
jer_type_encoder_f PublicSafetyAndRoadWorkerActivity_encode_jer;
per_type_decoder_f PublicSafetyAndRoadWorkerActivity_decode_uper;
per_type_encoder_f PublicSafetyAndRoadWorkerActivity_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PublicSafetyAndRoadWorkerActivity_H_ */
#include "asn_internal.h"
