/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TravelerInformation"
 * 	found in "../j2735/J2735-TravelerInformation.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_Radius_B12_H_
#define	_Radius_B12_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Radius-B12 */
typedef long	 Radius_B12_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Radius_B12_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Radius_B12;
asn_struct_free_f Radius_B12_free;
asn_struct_print_f Radius_B12_print;
asn_constr_check_f Radius_B12_constraint;
jer_type_encoder_f Radius_B12_encode_jer;
per_type_decoder_f Radius_B12_decode_uper;
per_type_encoder_f Radius_B12_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Radius_B12_H_ */
#include "asn_internal.h"
