/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "../j2735/J2735-Common.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_RegionId_H_
#define	_RegionId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RegionId */
typedef long	 RegionId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RegionId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RegionId;
asn_struct_free_f RegionId_free;
asn_struct_print_f RegionId_print;
asn_constr_check_f RegionId_constraint;
jer_type_encoder_f RegionId_encode_jer;
per_type_decoder_f RegionId_decode_uper;
per_type_encoder_f RegionId_encode_uper;
#define RegionId_noRegion	((RegionId_t)0)
#define RegionId_addGrpA	((RegionId_t)1)
#define RegionId_addGrpB	((RegionId_t)2)
#define RegionId_addGrpC	((RegionId_t)3)

#ifdef __cplusplus
}
#endif

#endif	/* _RegionId_H_ */
#include "asn_internal.h"
