/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RTCMcorrections"
 * 	found in "../j2735/J2735-RTCMcorrections.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_RTCM_Revision_H_
#define	_RTCM_Revision_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RTCM_Revision {
	RTCM_Revision_unknown	= 0,
	RTCM_Revision_rtcmRev2	= 1,
	RTCM_Revision_rtcmRev3	= 2,
	RTCM_Revision_reserved	= 3
	/*
	 * Enumeration is extensible
	 */
} e_RTCM_Revision;

/* RTCM-Revision */
typedef long	 RTCM_Revision_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RTCM_Revision_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RTCM_Revision;
extern const asn_INTEGER_specifics_t asn_SPC_RTCM_Revision_specs_1;
asn_struct_free_f RTCM_Revision_free;
asn_struct_print_f RTCM_Revision_print;
asn_constr_check_f RTCM_Revision_constraint;
jer_type_encoder_f RTCM_Revision_encode_jer;
per_type_decoder_f RTCM_Revision_decode_uper;
per_type_encoder_f RTCM_Revision_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RTCM_Revision_H_ */
#include "asn_internal.h"
