/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SPAT"
 * 	found in "../j2735/J2735-SPAT.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_SPAT_TimeMark_H_
#define	_SPAT_TimeMark_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SPAT_TimeMark */
typedef long	 SPAT_TimeMark_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SPAT_TimeMark_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SPAT_TimeMark;
asn_struct_free_f SPAT_TimeMark_free;
asn_struct_print_f SPAT_TimeMark_print;
asn_constr_check_f SPAT_TimeMark_constraint;
jer_type_encoder_f SPAT_TimeMark_encode_jer;
per_type_decoder_f SPAT_TimeMark_decode_uper;
per_type_encoder_f SPAT_TimeMark_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SPAT_TimeMark_H_ */
#include "asn_internal.h"
