/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "../j2735/J2735-Common.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_SSPindex_H_
#define	_SSPindex_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SSPindex */
typedef long	 SSPindex_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SSPindex_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SSPindex;
asn_struct_free_f SSPindex_free;
asn_struct_print_f SSPindex_print;
asn_constr_check_f SSPindex_constraint;
jer_type_encoder_f SSPindex_encode_jer;
per_type_decoder_f SSPindex_decode_uper;
per_type_encoder_f SSPindex_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SSPindex_H_ */
#include "asn_internal.h"
