/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SPAT"
 * 	found in "../j2735/J2735-SPAT.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_TimeIntervalConfidence_H_
#define	_TimeIntervalConfidence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TimeIntervalConfidence */
typedef long	 TimeIntervalConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TimeIntervalConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TimeIntervalConfidence;
asn_struct_free_f TimeIntervalConfidence_free;
asn_struct_print_f TimeIntervalConfidence_print;
asn_constr_check_f TimeIntervalConfidence_constraint;
jer_type_encoder_f TimeIntervalConfidence_encode_jer;
per_type_decoder_f TimeIntervalConfidence_decode_uper;
per_type_encoder_f TimeIntervalConfidence_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeIntervalConfidence_H_ */
#include "asn_internal.h"
