/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TravelerInformation"
 * 	found in "../j2735/J2735-TravelerInformation.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_TravelerInfoType_H_
#define	_TravelerInfoType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TravelerInfoType {
	TravelerInfoType_unknown	= 0,
	TravelerInfoType_advisory	= 1,
	TravelerInfoType_roadSignage	= 2,
	TravelerInfoType_commercialSignage	= 3
	/*
	 * Enumeration is extensible
	 */
} e_TravelerInfoType;

/* TravelerInfoType */
typedef long	 TravelerInfoType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TravelerInfoType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TravelerInfoType;
extern const asn_INTEGER_specifics_t asn_SPC_TravelerInfoType_specs_1;
asn_struct_free_f TravelerInfoType_free;
asn_struct_print_f TravelerInfoType_print;
asn_constr_check_f TravelerInfoType_constraint;
jer_type_encoder_f TravelerInfoType_encode_jer;
per_type_decoder_f TravelerInfoType_decode_uper;
per_type_encoder_f TravelerInfoType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TravelerInfoType_H_ */
#include "asn_internal.h"
