/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "../j2735/J2735-Common.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_VertOffset_B09_H_
#define	_VertOffset_B09_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VertOffset-B09 */
typedef long	 VertOffset_B09_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VertOffset_B09_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VertOffset_B09;
asn_struct_free_f VertOffset_B09_free;
asn_struct_print_f VertOffset_B09_print;
asn_constr_check_f VertOffset_B09_constraint;
jer_type_encoder_f VertOffset_B09_encode_jer;
per_type_decoder_f VertOffset_B09_decode_uper;
per_type_encoder_f VertOffset_B09_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VertOffset_B09_H_ */
#include "asn_internal.h"
