/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SPAT"
 * 	found in "../j2735/J2735-SPAT.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_WaitOnStopline_H_
#define	_WaitOnStopline_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"

#ifdef __cplusplus
extern "C" {
#endif

/* WaitOnStopline */
typedef BOOLEAN_t	 WaitOnStopline_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WaitOnStopline;
asn_struct_free_f WaitOnStopline_free;
asn_struct_print_f WaitOnStopline_print;
asn_constr_check_f WaitOnStopline_constraint;
jer_type_encoder_f WaitOnStopline_encode_jer;
per_type_decoder_f WaitOnStopline_decode_uper;
per_type_encoder_f WaitOnStopline_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _WaitOnStopline_H_ */
#include "asn_internal.h"
