/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ProbeVehicleData"
 * 	found in "../j2735/J2735-ProbeVehicleData.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_WheelSensorStatus_H_
#define	_WheelSensorStatus_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WheelSensorStatus {
	WheelSensorStatus_off	= 0,
	WheelSensorStatus_on	= 1,
	WheelSensorStatus_notDefined	= 2,
	WheelSensorStatus_notSupported	= 3
} e_WheelSensorStatus;

/* WheelSensorStatus */
typedef long	 WheelSensorStatus_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_WheelSensorStatus_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_WheelSensorStatus;
extern const asn_INTEGER_specifics_t asn_SPC_WheelSensorStatus_specs_1;
asn_struct_free_f WheelSensorStatus_free;
asn_struct_print_f WheelSensorStatus_print;
asn_constr_check_f WheelSensorStatus_constraint;
jer_type_encoder_f WheelSensorStatus_encode_jer;
per_type_decoder_f WheelSensorStatus_decode_uper;
per_type_encoder_f WheelSensorStatus_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _WheelSensorStatus_H_ */
#include "asn_internal.h"
