#!/usr/bin/env bash
set -euo pipefail

./tooling/lint.sh --non-interactive

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "develop" ]; then
  echo "You can't commit directly to develop branch"
  exit 1
fi
