/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "J2540ITIS"
 * 	found in "../j2540/J2540_2_20200917.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_AlternateRoute_H_
#define	_AlternateRoute_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AlternateRoute {
	AlternateRoute_detour_where_possible	= 8449,
	AlternateRoute_no_detour_available	= 8450,
	AlternateRoute_follow_signs	= 8451,
	AlternateRoute_follow_detour_signs	= 8452,
	AlternateRoute_follow_special_detour_markers	= 8453,
	AlternateRoute_do_not_follow_detour_signs	= 8454,
	AlternateRoute_detour_in_operation	= 8455,
	AlternateRoute_follow_local_detour	= 8456,
	AlternateRoute_compulsory_detour_in_operation	= 8457,
	AlternateRoute_no_suitable_detour_available	= 8458,
	AlternateRoute_detour_is_no_longer_recommended	= 8459,
	AlternateRoute_local_drivers_are_recommended_to_avoid_the_area	= 8460,
	AlternateRoute_trucks_are_recommended_to_avoid_the_area	= 8461,
	AlternateRoute_consider_alternate_route	= 8462,
	AlternateRoute_consider_alternate_parking	= 8463,
	AlternateRoute_consider_alternate_destination	= 8464,
	AlternateRoute_consider_alternate_area	= 8465,
	AlternateRoute_snow_route	= 8466,
	AlternateRoute_emergency_snow_route	= 8467,
	AlternateRoute_evacuation_route	= 8468,
	AlternateRoute_truck_route	= 8469,
	AlternateRoute_hazardous_materials_route	= 8470,
	AlternateRoute_detour	= 8471
} e_AlternateRoute;

/* AlternateRoute */
typedef long	 AlternateRoute_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AlternateRoute_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AlternateRoute;
asn_struct_free_f AlternateRoute_free;
asn_struct_print_f AlternateRoute_print;
asn_constr_check_f AlternateRoute_constraint;
jer_type_encoder_f AlternateRoute_encode_jer;
per_type_decoder_f AlternateRoute_decode_uper;
per_type_encoder_f AlternateRoute_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AlternateRoute_H_ */
#include "asn_internal.h"
