/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "J2540ITIS"
 * 	found in "../j2540/J2540_2_20200917.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_Disasters_H_
#define	_Disasters_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Disasters {
	Disasters_flash_flood	= 3073,
	Disasters_major_flood	= 3074,
	Disasters_reservoir_failure	= 3075,
	Disasters_levee_failure	= 3076,
	Disasters_tsunami	= 3077,
	Disasters_tidal_wave	= 3078,
	Disasters_volcanic_eruption	= 3079,
	Disasters_ash_fall	= 3080,
	Disasters_lava_flow	= 3081,
	Disasters_serious_fire	= 3082,
	Disasters_forest_fire	= 3083,
	Disasters_wildfire	= 3084,
	Disasters_building_fire	= 3085,
	Disasters_brush_fire	= 3086,
	Disasters_grass_fire	= 3087,
	Disasters_fire_danger_extreme	= 3088,
	Disasters_fire_danger_very_high	= 3089,
	Disasters_fire_danger_high	= 3090,
	Disasters_fire_danger_medium	= 3091,
	Disasters_fire_danger_low	= 3092,
	Disasters_earthquake_damage	= 3093,
	Disasters_air_crash	= 3094,
	Disasters_rail_crash	= 3095,
	Disasters_toxic_release	= 3096,
	Disasters_toxic_leak	= 3097,
	Disasters_radioactive_release	= 3098,
	Disasters_radiation_hazard	= 3099,
	Disasters_reactor_leakage	= 3100,
	Disasters_explosion	= 3101,
	Disasters_major_hazardous_materials_fire	= 3102,
	Disasters_major_hazardous_materials_release	= 3103,
	Disasters_disaster_cleared	= 3199
} e_Disasters;

/* Disasters */
typedef long	 Disasters_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Disasters_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Disasters;
asn_struct_free_f Disasters_free;
asn_struct_print_f Disasters_print;
asn_constr_check_f Disasters_constraint;
jer_type_encoder_f Disasters_encode_jer;
per_type_decoder_f Disasters_decode_uper;
per_type_encoder_f Disasters_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Disasters_H_ */
#include "asn_internal.h"
