/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "J2540ITIS"
 * 	found in "../j2540/J2540_2_20200917.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_ITIStext_H_
#define	_ITIStext_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IA5String.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ITIStext */
typedef IA5String_t	 ITIStext_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ITIStext_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ITIStext;
asn_struct_free_f ITIStext_free;
asn_struct_print_f ITIStext_print;
asn_constr_check_f ITIStext_constraint;
jer_type_encoder_f ITIStext_encode_jer;
per_type_decoder_f ITIStext_decode_uper;
per_type_encoder_f ITIStext_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ITIStext_H_ */
#include "asn_internal.h"
