/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "J2540ITIS"
 * 	found in "../j2540/J2540_2_20200917.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_SuggestionAdvice_H_
#define	_SuggestionAdvice_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SuggestionAdvice {
	SuggestionAdvice_why_not_ride_share	= 6657,
	SuggestionAdvice_is_this_your_no_ride_day	= 6658,
	SuggestionAdvice_why_not_use_transit	= 6659,
	SuggestionAdvice_why_not_park_and_ride	= 6660,
	SuggestionAdvice_why_not_try_paratransit	= 6661,
	SuggestionAdvice_why_not_travel_by_rail	= 6662,
	SuggestionAdvice_why_not_use_the_subway	= 6663,
	SuggestionAdvice_why_not_try_rapid_transit	= 6664,
	SuggestionAdvice_why_not_travel_by_bus	= 6665,
	SuggestionAdvice_your_parking_ticket_covers_the_return_ride	= 6666,
	SuggestionAdvice_avoid_the_rush_hour	= 6667,
	SuggestionAdvice_do_not_allow_unnecessary_gaps	= 6668,
	SuggestionAdvice_follow_the_vehicle_in_front_smoothly	= 6669,
	SuggestionAdvice_do_not_slow_down_unnecessarily	= 6670,
	SuggestionAdvice_watch_for_muggers	= 6671,
	SuggestionAdvice_watch_for_pickpockets	= 6672,
	SuggestionAdvice_watch_for_thieves	= 6673,
	SuggestionAdvice_sorry_for_any_delay	= 6674,
	SuggestionAdvice_thank_you_for_your_understanding	= 6675,
	SuggestionAdvice_we_appreciate_your_patience	= 6676,
	SuggestionAdvice_we_are_grateful_for_your_cooperation	= 6677,
	SuggestionAdvice_share_the_road	= 6678
} e_SuggestionAdvice;

/* SuggestionAdvice */
typedef long	 SuggestionAdvice_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SuggestionAdvice_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SuggestionAdvice;
asn_struct_free_f SuggestionAdvice_free;
asn_struct_print_f SuggestionAdvice_print;
asn_constr_check_f SuggestionAdvice_constraint;
jer_type_encoder_f SuggestionAdvice_encode_jer;
per_type_decoder_f SuggestionAdvice_decode_uper;
per_type_encoder_f SuggestionAdvice_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SuggestionAdvice_H_ */
#include "asn_internal.h"
