/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "J2540ITIS"
 * 	found in "../j2540/J2540_2_20200917.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_TravelerGroupAffected_H_
#define	_TravelerGroupAffected_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TravelerGroupAffected {
	TravelerGroupAffected_through_traffic	= 9473,
	TravelerGroupAffected_holiday_traffic	= 9474,
	TravelerGroupAffected_residents	= 9475,
	TravelerGroupAffected_visitors	= 9476,
	TravelerGroupAffected_long_distance_traffic	= 9477,
	TravelerGroupAffected_local_traffic	= 9478,
	TravelerGroupAffected_regional_traffic	= 9479,
	TravelerGroupAffected_arrivals	= 9480,
	TravelerGroupAffected_departures	= 9481,
	TravelerGroupAffected_airline_travelers	= 9482,
	TravelerGroupAffected_commuter_airline_travelers	= 9483,
	TravelerGroupAffected_domestic_airline_travelers	= 9484,
	TravelerGroupAffected_international_airline_travelers	= 9485,
	TravelerGroupAffected_pedestrians	= 9486,
	TravelerGroupAffected_bicyclists	= 9487
} e_TravelerGroupAffected;

/* TravelerGroupAffected */
typedef long	 TravelerGroupAffected_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TravelerGroupAffected_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TravelerGroupAffected;
asn_struct_free_f TravelerGroupAffected_free;
asn_struct_print_f TravelerGroupAffected_print;
asn_constr_check_f TravelerGroupAffected_constraint;
jer_type_encoder_f TravelerGroupAffected_encode_jer;
per_type_decoder_f TravelerGroupAffected_decode_uper;
per_type_encoder_f TravelerGroupAffected_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TravelerGroupAffected_H_ */
#include "asn_internal.h"
