/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "J2540ITIS"
 * 	found in "../j2540/J2540_2_20200917.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_UnusualDriving_H_
#define	_UnusualDriving_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UnusualDriving {
	UnusualDriving_vehicle_traveling_wrong_way	= 1793,
	UnusualDriving_reckless_driver	= 1794,
	UnusualDriving_prohibited_vehicle_on_roadway	= 1795,
	UnusualDriving_emergency_vehicles_on_roadway	= 1796,
	UnusualDriving_high_speed_emergency_vehicles	= 1797,
	UnusualDriving_high_speed_chase	= 1798,
	UnusualDriving_dangerous_vehicle_warning_cleared	= 1918,
	UnusualDriving_emergency_vehicle_warning_cleared	= 1919
} e_UnusualDriving;

/* UnusualDriving */
typedef long	 UnusualDriving_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UnusualDriving_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UnusualDriving;
asn_struct_free_f UnusualDriving_free;
asn_struct_print_f UnusualDriving_print;
asn_constr_check_f UnusualDriving_constraint;
jer_type_encoder_f UnusualDriving_encode_jer;
per_type_decoder_f UnusualDriving_decode_uper;
per_type_encoder_f UnusualDriving_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UnusualDriving_H_ */
#include "asn_internal.h"
