/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "J2540ITIS"
 * 	found in "../j2540/J2540_2_20200917.asn"
 * 	`asn1c -S ../asn1c/skeletons/ -fcompound-names -no-gen-example -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -fincludes-quoted -findirect-choice`
 */

#ifndef	_WinterDrivingIndex_H_
#define	_WinterDrivingIndex_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WinterDrivingIndex {
	WinterDrivingIndex_driving_conditions_good	= 6401,
	WinterDrivingIndex_driving_conditions_fair	= 6402,
	WinterDrivingIndex_difficult_driving_conditions	= 6403,
	WinterDrivingIndex_very_difficult_driving_conditions	= 6404,
	WinterDrivingIndex_hazardous_driving_conditions	= 6405,
	WinterDrivingIndex_extremely_hazardous_driving_conditions	= 6406
} e_WinterDrivingIndex;

/* WinterDrivingIndex */
typedef long	 WinterDrivingIndex_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_WinterDrivingIndex_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_WinterDrivingIndex;
asn_struct_free_f WinterDrivingIndex_free;
asn_struct_print_f WinterDrivingIndex_print;
asn_constr_check_f WinterDrivingIndex_constraint;
jer_type_encoder_f WinterDrivingIndex_encode_jer;
per_type_decoder_f WinterDrivingIndex_decode_uper;
per_type_encoder_f WinterDrivingIndex_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _WinterDrivingIndex_H_ */
#include "asn_internal.h"
